#---------------------------
# fiberless
# 一款简单轻量的HEXO主题
# Author: cijiugechu
# 
#---------------------------

# page title  
title: fiberless

# website address
site: 

# blog author
author: cijiugechu

# navbar menus
nav:
  home: /
  categories: /categories
  tags: /tags
  about: /about

language:
  - en
  - zh-Hans

# view more: https://github.com/highlightjs/highlight.js
# available themes: zenburn | rainbow | light | atom
highlight_theme: zenburn

# copyright info of posts
post_copyright:
  enable: true
  license: CC BY-NC-SA 4.0
  license_url: https://creativecommons.org/licenses/by-nc-sa/4.0/

# footer settings
since: 2019

# picture resource( stored in /source/img folder )
favicon: 
profilepic: /img/profilepic.png

# page about you
about:
  name:
  Bio: 歲月은흘러가도，山川은안다。
  github:
  twitter: 
  email:
  telegram:

